### ISSUE TITLE
json_to_sqs_tacoxdna.py bug fix for complementary bases, automatic linear scaffold start site detection and circular scaffold extension

### ISSUE THREAD

**Issue by PeiskerT** [Mishrito/oxDNA-handy-scripts#1]
Hi @Mishrito,

first of all, thank you very much for the json_to_sqs_tacoxdna.py script. It helped me a lot to conduct sequence specific DNA origami simulations from cadnano in oxDNA. However, I believe there is a small bug in your code that causes some of the sequences that extend over multiple virtual helixes to be incorrectly converted. I have already fixed the bug and also extended your code to be able to automatically determine the starting position of linear scaffold instead of checking the user input. Moreover, the code is now able to process designs with circular scaffold, too. Would you like to receive a pull request with my updates so that you and/or other members of the community can benefit from the new code?

Thanks and best regards,

Tim

**Comment by MishraS-S** [comment]
Hey there Tim

Thank you very much for improving and extending the code. This was just a
quick'n dirty script I had whipped out to help myself perform sequence
specific simulations and while I do have it in a public repository, I
hadn't realistically expected anyone to find their way here.

About the sequence bug, I was initially told that the script provided by
tacoxdna reads the sequence in 3' to 5' direction and since the direction
of the vhelix switches as you go down a helix I had added a complementary
function but turns out it doesn't actually do that so the compl function
ended up being completely unnecessary. I had fixed it on my end but had
forgotten to commit 😅😅 (and I do understand that completely defeats the
point of having version control in the first place). Unless you were
talking about a different bug in which please ignore the above.

Either way, thank you again for fixing and improving the script, and yes
please do send a pull request my way, I would be glad to accept it.

Shubham

**Comment by PeiskerT** [comment]
Hey Shubham,

yes that's exactly what I meant by the bug. I just removed the parts where it used the complementary function and it worked fine after that. 

Great I sent you a pull request. Let me know what you think.

Tim
